const bosses = [
  // bosses will be much stronger than normal enemies
  // may very rarely spawn in the overworld, most often found in designated areas (dungeons)
  // enemy ID's first digit tells which game they come from
  // 1 = zelda, 2 = mario, 3 = pokemon, 4 = deltarune
  // for enemies not from zelda, they will have their own special battle UI, sound effects, background music, and more
  // the player will be warned non-zelda bosses are nearby in some fashion, possibly audio cues
  { // spawns in 1st and 7th dungeon
    name: "Aquamentus",
    id: 10,
    size: [2,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Triple Fireball",
        atkSpeed: "normal",
        atkType: "ranged",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 2nd dungeon, is a miniboss in 5th/7th dungeon
    name: "Dodongo",
    id: 11,
    size: [2,2],
    movementType: "normal",
    enemyType: "dodongo",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Bash",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 3rd dungeon, is a miniboss in 4th/8th dungeon
    name: "Manhandla",
    id: 12,
    size: [3,3],
    movementType: "normal",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Icicle Shard",
        atkSpeed: "slow",
        atkType: "ranged",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 4th dungeon with 2 heads. Is a miniboss in 6th dungeon with 3 heads and in 8th dungeon with 4 heads
    name: "Gleeok",
    id: 13,
    size: [2,3],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Ice Breath",
        atkSpeed: "normal",
        atkType: "ranged",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 5th dungeon, is a miniboss in 7th dungeon
    name: "Digdogger",
    id: 14,
    size: [2,2],
    movementType: "normal",
    enemyType: "digdogger",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Bash",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 6th dungeon, is a miniboss in 8th dungeon
    name: "Gohma",
    id: 15,
    size: [3,1],
    movementType: "hop",
    enemyType: "gohma",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Close Eye",
        atkSpeed: "fast",
        atkType: "buff",
        atkAff: "support",
      },
      {
        name: "Open Eye",
        atkSpeed: "fast",
        atkType: "debuff",
        atkAff: "support",
      },
      {
        name: "Sticky Web",
        atkSpeed: "normal",
        atkType: "debuff",
        atkAff: "support",
        buffType: "speed",
        buffMultiplier: 2,
        buffDuration: 3,
      },
      {
        name: "Fireball",
        atkSpeed: "fast",
        atkType: "ranged",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // spawns in 9th (final) dungeon
    name: "Ganon",
    id: 16,
    size: [2,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Invisibility",
        atkSpeed: "fast",
        atkType: "buff",
        atkAff: "support",
      },
      {
        name: "Fireball",
        atkSpeed: "normal",
        atkType: "ranged",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // mario, spawns in peach's castle
    name: "Red Plumber",
    id: 20,
    size: [1,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Jump",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Hammer",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Bros' Attack",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // luigi, spawns in peach's castle
    name: "Green Plumber",
    id: 21,
    size: [1,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Jump",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Hammer",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Bros' Attack",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // bowser, spawns in bowser's castle
    name: "King of the Koopas",
    id: 22,
    size: [3,3],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Punch",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Flame",
        atkSpeed: "normal",
        atkType: "ranged",
        atkAff: "fire",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Vacuum",
        atkSpeed: "normal",
        atkType: "debuff",
        atkAff: "support",
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // red, spawns in mt. silver summit
    name: "Pocket Monster Champion",
    id: 30,
    size: [1,1],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    team: ["Pikachu", "Espeon", "Snorlax", "Venusaur", "Charizard", "Blastoise"],
    currentPKMN: "Pikachu",
    attacks: [
      {
        name: "Send Out PKMN",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // kris, spawns in castle town
    name: "Empty Boy",
    id: 40,
    size: [1,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Fight",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Act",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Mercy",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Guard",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // susie, spawns in castle town
    name: "Rowdy Horse",
    id: 41,
    size: [1,2],
    movementType: "idle",
    enemyType: "normal",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Fight",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Magic",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Mercy",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Guard",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
  { // ralsei, spawns in castle town
    name: "Gentle Goat",
    id: 42,
    size: [1,2],
    movementType: "idle",
    baseStats: {
      maxHP: 0,
      atk: 0,
      def: 0,
      spd: 0,
      evasion: 0,
    },
    attacks: [
      {
        name: "Fight",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Magic",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Item",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Mercy",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
      {
        name: "Guard",
        atkSpeed: "normal",
        atkType: "melee",
        atkAff: "hit",
        baseDMG: 0,
        accuracy: 100,
      },
    ],
  },
];